---
# Общий комменатрий к конфигу - во всех путях (особенно на локальной машине) 
# необходимо использовать символы обратного слеша (/), либо двойной прямой (\\), 
# ибо одиночный прямой является спецсимволом

# Версия конфигурации настроек.
version: v1


# В блоке remote описывается путь к дистрибутиву клиента.
# В версии v1 поддерживается обновление только по фтп.
remote:
  # Адрес сервера
  host: ftpserver
  # Путь к дистрибутиву
  path: /app1/staging/app1.zip
  # Логин и пароль к серверу
  user: user
  pass: s3cr3tpassw0RD

# В блоке local описываются настройки рабочего места.
local:
  # Расположение установленной копии app1.
  path: C:/vendor1/staging
  # Стартовый файл app1 для рабочего места
  start: go_staging.bat
  # Расположение конфигов и стартовых файлов
  conf: C:/vendor1/conf
  bin: C:/vendor1/bin

# В блоке update описываются настройки обновления
update:
  # Расположение логов модуля обновления
  log: c:/vendor1/app1_update/staging
  # Расположение архивной копии app1
  archive: c:/vendor1/archive/staging
  # Формат имени папки
  # name_format: 2006_01_02_15_04
  # Сжимать ли архивную копию или нет.
  # compress: true
  # Использовать ли проверку по хэшу
  #hash: true # NIY

# В блоке system описываются настройки приложения.
system:
  # Принудительное обновление.
  force: true
  # Разница времени на фтп и реального времени
  shift: 3
  # Таймаут связи с фтп сервером.
  #timeout: 15